### ISSUE TITLE
how can seq2seq-attention work on Chinese conversation corpus？

### ISSUE THREAD

**Issue by brandyaptx** [rsarxiv/seq2seq-attention#3]
If  change the wiki conversation dataset to Chinese conversation dataset（ex. http://data.noahlab.com.hk/conversation/）, how to rewrite the code?

**Comment by rsarxiv** [comment]
If you change the dataset,  you need to rewrite the preprocessing file `bot.py`, maybe add Chinese Tokenize function to process your data. Good luck!

**Comment by brandyaptx** [comment]
thanks, I will try.

**Comment by loveJasmine** [comment]
would you provide the dataset http://data.noahlab.com.hk/conversation/ ?
@brandyaptx 
it seems unavailable now
