### ISSUE TITLE
How to post valid data to server?

### ISSUE THREAD

**Issue by juncaofish** [rsarxiv/seq2seq-attention#5]
Client side:
➜  seq2seq-attention git:(master) ✗ curl http://0.0.0.0:8080/bot -d 'input=hello'
<html><body><h1>Error: 500</h1><p>Internal Server Error</p><p>/Users/juncaofish/torch/install/share/lua/5.1/nn/MM.lua:22: attempt to call method 'nDimension' (a nil value)</p></body></html>%

Server side:
➜  seq2seq-attention git:(master) ✗ th server.lua
Listening on 0.0.0.0:8080
ERROR: /Users/juncaofish/torch/install/share/lua/5.1/nn/MM.lua:22: attempt to call method 'nDimension' (a nil value)

Is there something wrong?

**Comment by rsarxiv** [comment]
I think you need to modify the url address with 127.0.0.1:8080/bot, not 0.0.0.0

**Comment by juncaofish** [comment]
Yeah, I've tried that url address but nothing changed.

➜  seq2seq-attention git:(master) ✗ curl http://127.0.0.1:8080/bot -d 'input=hello'
<html><body><h1>Error: 500</h1><p>Internal Server Error</p><p>/Users/juncaofish/torch/install/share/lua/5.1/nn/MM.lua:22: attempt to call method 'nDimension' (a nil value)</p></body></html>%

But this works for me.
➜  seq2seq-attention git:(master) ✗ th test.lua -text "hello"
{
  1 : " enough with was releases > published was boxes well those trade -- sunday '' currently interests it page it"
  2 : " here a wikipedia war\ < each , en \ ? thus ; misspelled . : notice . sources of"
  3 : " to . ) bcc from and . focusing of '' our ; between is ! , but into ,"
}

**Comment by rsarxiv** [comment]
Hi, thanks for your bug report. It is a small bug in file `sample.lua`, I fixed it just now, hope it works.
It should be the same as file `test.lua`, but I forgot to fix it before. You can try the new version now!

**Comment by juncaofish** [comment]
Sorry for replying late. I pull the latest code, and get what I want. Thanks.
